config/routes.rb
Rails.application.routes.draw do

  resources :scores
  resources :users

  root 'game#index'

  get    '/login',          to: 'sessions#new'
  post   '/login',          to: 'sessions#create'
  delete '/logout',         to: 'sessions#destroy'
  get    '/signup',         to: 'users#new'
  post   '/signup',         to: 'users#create'
  get    '/about',          to: 'static_pages#about'
  get    '/leaderboard',    to: 'scores#leaderboard'
  get    '/api/scores/new', to: 'scores#new_api_call'
  post   '/api/scores/new', to: 'scores#create_api_call'

end

app/models/score.rb
class Score < ApplicationRecord
  belongs_to :user
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController

  skip_before_action :logged_in_authorized, only: [:leaderboard, :new_api_call, :create_api_call]
  skip_before_action :admin_authorized, only: [:leaderboard, :new_api_call, :create_api_call]
  before_action :set_score, only: %i[ show edit update destroy ]

  # GET /scores or /scores.json
  def index
    @scores = Score.all
  end

  def leaderboard
    @scores = Score.all.sort_by(&:val).reverse.first(10)
    render :template => 'scores/leaderboard'
  end

  # GET /scores/1 or /scores/1.json
  def show
  end

  # GET /scores/new
  def new
    @score = Score.new
  end

  # GET /api/scores/new
  def new_api_call
    @score = Score.new
  end

  # GET /scores/1/edit
  def edit
  end

  # POST /scores or /scores.json
  def create
    @score = Score.new(score_params)

    respond_to do |format|
      if @score.save
        format.html { redirect_to score_url(@score), notice: "Score was successfully created." }
        format.json { render :show, status: :created, location: @score }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /api/scores/new
  def create_api_call
    @score = Score.new(score_params)

    respond_to do |format|
      if @score.save
        format.json { render :show, status: :created, location: @score }
      else
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scores/1 or /scores/1.json
  def update
    respond_to do |format|
      if @score.update(score_params)
        format.html { redirect_to score_url(@score), notice: "Score was successfully updated." }
        format.json { render :show, status: :ok, location: @score }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scores/1 or /scores/1.json
  def destroy
    @score.destroy

    respond_to do |format|
      format.html { redirect_to scores_url, notice: "Score was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_score
      @score = Score.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def score_params
      params.require(:score).permit(:val, :user_id)
    end
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/views/scores/_form.html.erb
<%= form_with(model: score, class: 'page-form') do |form| %>
  <% if score.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(score.errors.count, "error") %> prohibited this score from being saved:</h2>

      <ul>
        <% score.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :val, 'Score', style: "display: block" %>
    <%= form.number_field :val %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/scores/_form_api_call.html.erb
<%= form_with(model: score) do |form| %>
  <% if score.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(score.errors.count, "error") %> prohibited this score from being saved:</h2> 

      <ul>
        <% score.errors.each do |error| %> 
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :val, style: "display: block" %>
    <%= form.number_field :val %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.submit :id => "testScoresApiSubmit" %>
  </div>
<% end %>

app/views/scores/_score.html.erb
<div id="<%= dom_id score %>">

<div id="scores" class="section-narrow">
  <table class="table">
    <tr>
      <th>score</th>
      <th>user</th>
      <th>date</th>
    <tr>
      <tr id="<%= dom_id score %>">
        <td><%= score.val %></td>
        <td><%= User.find_by_id(score.user_id).username %></td>
        <td><%= score.created_at.strftime("%_m/%-d/%y") %>
      </tr>
  </table>
</div>

</div>

app/views/scores/edit.html.erb
<h1>Edit Score</h1>

<%= render "form", score: @score %>

<br>

<div>
  <%= link_to "Show score", @score, class: 'btn btn-secondary me-2' %> 
  <%= link_to "Back to scores", scores_path, class: 'btn btn-secondary
  ' %>
</div>

app/views/scores/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Scores</h1>

<%= link_to "New score", new_score_path, class: 'btn btn-primary btn-lg mb-4' %>

<div class="section-narrow">
  <table class="table">
    <tr>
      <th>#</th>
      <th>score</th>
      <th>user</th>
      <th>date</th>
      <th></th>
    <tr>
    <% @scores.each_with_index do |score, index| %>
      <tr id="<%= dom_id score %>">
        <td><%= index + 1 %></td>
        <td><%= score.val %></td>
        <td><%= User.find_by_id(score.user_id).username %></td>
        <td><%= score.created_at.strftime("%_m/%-d/%y") %>
        <td><%= link_to "Edit", 'scores/' + score.id.to_s + '/edit', class: 'btn btn-secondary btn-sm' %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/scores/leaderboard.html.erb
<% provide(:page, 'Leaderboard') %>
<p style="color: green"><%= notice %></p>

<h1>Leaderboard</h1>

<div id="scores" class="section-narrow">
  <table class="table">
    <tr>
      <th>#</th>
      <th>score</th>
      <th>level</th>
      <th>user</th>
      <th>date</th>
      <th>game<br>version*</th>
    <tr>
    <% @scores.each_with_index do |score, index| %>
      <% @user = User.find_by_id(score.user_id) %>
      <tr id="<%= dom_id score %>">
        <td><%= index + 1 %></td>
        <td><%= score.val %></td>
        <td><%= get_level(score.val) %></td>
        <td><img class='leaderboard-avatar' src='https://i.pravatar.cc/20?img=<%= @user.pravatar.to_s %>' alt='avatar' width='20' /><%= @user.username %></td>
        <td><%= score.created_at.strftime("%_m/%-d/%y") %></td>
        <td><%= get_version(score.created_at) =%></td>
      </tr>
    <% end %>
  </table>
  <p class='footnote'>* As the app development goes through changes, scores from different game vesions may not be comparable</p>
</div>

app/views/scores/new.html.erb
<h1>New score</h1>

<%= render "form", score: @score %>

<br>

<div>
  <%= link_to "Back to scores", scores_path, class: 'btn btn-secondary' %>
</div>

app/views/scores/new_api_call.html.erb
<h1>New API Call Test</h1>

<%= render "form_api_call", score: @score %>

<br>

<div>
  <%= link_to "Back to scores", scores_path %>
</div>

app/views/scores/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @score %>

<div>
  <% if current_user_is_admin? %>
    <%= link_to "Edit score", edit_score_path(@score), class: 'btn btn-primary me-1' %> 
  <% end %> 
  <%= link_to "Back to scores", scores_path, class: 'btn btn-secondary me-1' %>
  <%= button_to "Destroy score", @score, method: :delete, class: 'btn btn-danger' %>
</div>